#ifndef PATCH_H
#define PATCH_H

#include <QtSql>
#include <cmath>
#include <iostream>
#include <fstream>
#include "node.h"

using namespace std;

/**
 * @brief The Patch class
 * This class allows to calculate all instructions for the user in order
 * to follow the shortest path generated by {@link Dijkstra} class
 */
class Patch
{
public:
    Patch();
    bool belong(Node*, Node*);
    vector <string> calcPatch(vector<Node*>);
    float checkAngle(Node*, Node*, Node*);
    void genTxt(vector<string>);

private:
    float distance;
    string curRoad;
};

#endif // PATCH_H
